= twosh(1)
Samuel Wilson
:doctype: manpage

== Name

twosh - Two Shell. A command language interpreter shell made for learning by building.

== Synopsis

*twosh*

== Description

`twosh` is a command language interpreter. It is intended to operate like any POSIX standard `sh` utility. It currently implements only the most basic features. It follows GNU Bash as inspiration a reference for development.

== Builtins

=== cd

Change the current working directory.

=== exit

Stop the `twosh` process.

== Development

Two Shell has been developed on Manjaro Ornara 21.0 - https://manjaro.org

Two Shell is built with the Free Pascal Compiler fpc 3.2.0 - https://www.freepascal.org

GNU Make 4.3 is used for build automation - https://www.gnu.org/software/make/

Asciidoctor 2.0.12 is used for creating the man pages - https://asciidoctor.org

GNU GDB 10.1 is used for debugging - https://www.gnu.org/software/gdb/

== Authors

Two Shell was written by Samuel Wilson.

== This Software is in the Public Domain

Two Shell and the contents of the Two Shell repository are in the public domain. Read the UNLICENSE file for details or read them at https://unlicense.org.

== Resources

Git source repository on GitHub: https://github.com/samWson/two-shell
