'\" t
.\"     Title: twosh
.\"    Author: Samuel Wilson
.\" Generator: Asciidoctor 2.0.12
.\"      Date: 2021-03-19
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "TWOSH" "1" "2021-03-19" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
twosh \- Two Shell. A command language interpreter shell made for learning by building.
.SH "SYNOPSIS"
.sp
\fBtwosh\fP
.SH "DESCRIPTION"
.sp
\f(CRtwosh\fP is a command language interpreter. It is intended to operate like any POSIX standard \f(CRsh\fP utility. It currently implements only the most basic features. It follows GNU Bash as inspiration a reference for development.
.SH "BUILTINS"
.SS "cd"
.sp
Change the current working directory.
.SS "exit"
.sp
Stop the \f(CRtwosh\fP process.
.SH "DEVELOPMENT"
.sp
Two Shell has been developed on Manjaro Ornara 21.0 \- \c
.URL "https://manjaro.org" "" ""
.sp
Two Shell is built with the Free Pascal Compiler fpc 3.2.0 \- \c
.URL "https://www.freepascal.org" "" ""
.sp
GNU Make 4.3 is used for build automation \- \c
.URL "https://www.gnu.org/software/make/" "" ""
.sp
Asciidoctor 2.0.12 is used for creating the man pages \- \c
.URL "https://asciidoctor.org" "" ""
.sp
GNU GDB 10.1 is used for debugging \- \c
.URL "https://www.gnu.org/software/gdb/" "" ""
.SH "AUTHORS"
.sp
Two Shell was written by Samuel Wilson.
.SH "THIS SOFTWARE IS IN THE PUBLIC DOMAIN"
.sp
Two Shell and the contents of the Two Shell repository are in the public domain. Read the UNLICENSE file for details or read them at \c
.URL "https://unlicense.org" "" "."
.SH "RESOURCES"
.sp
Git source repository on GitHub: \c
.URL "https://github.com/samWson/two\-shell" "" ""
.SH "AUTHOR"
.sp
Samuel Wilson